Repository thekimsplustwo/VanCityPropertyPulse, pull requests merged in 2023-07, with the labels that each got.

#110 ISSUE 94 and 109
  client/src/components/Property/MenuItems.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: frontend

#115 MongoDB connection. enable listing from database
  server/.env-sample
  server/.eslintrc
  server/package-lock.json
  server/package.json
  server/src/data/data.js
  server/src/data/raw.json
  server/src/models/home.js
  server/src/schemas/BaseSchema.js
  server/src/schemas/index.js
  server/src/schemas/properties.js
  server/src/schemas/propertyDetails.js
  server/src/schemas/rawProperties.js
  server/src/server.js
  server/src/services/home.js
Labels: backend, database

#108 ISSUE-107 Redux actions - add actions/reducers for searching options
  client/src/components/SearchOption/SearchButtons/BedSelect.js
  client/src/components/SearchOption/SearchButtons/HomeType.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/components/SearchOption/SearchInput.js
  client/src/pages/Home/Home.js
  client/src/redux/home/service.js
  client/src/redux/home/thunks.js
  client/src/redux/search/actionTypes.js
  client/src/redux/search/reducer.js
  client/src/redux/store.js
Labels: frontend

#117 feat: db schemas & data populating code
  server/src/data/data.js
  server/src/schemas/index.js
  server/src/schemas/likes.js
  server/src/schemas/properties.js
  server/src/schemas/rawProperties.js
  server/src/schemas/resetDatabase.js
  server/src/schemas/users.js
Labels: database

#121 ISSUE-93 feat: share button
  client/src/components/Property/MenuItems.js
Labels: frontend

#119 ISSUE-95, feat add Compare btn and nvigate to compare page
  client/src/components/Header/Menu.js
  client/src/components/Property/PropertyCard.css
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyGrid.js
  client/src/pages/Home/Home.js
  client/src/pages/Likes/Likes.js
Labels: frontend

#125 Home listing/ Detailed page with Zillow API + Likes API
  client/src/components/Property/MenuItems.js
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyGrid.js
  client/src/components/Property/PropertyTitle.js
  client/src/redux/likes/reducer.js
  server/.env-sample
  server/.eslintrc
  server/src/controller/home.js
  server/src/data/data.js
  server/src/data/rawPropertyDetails.json
  server/src/models/home.js
  server/src/models/likes.js
  server/src/models/mockLikes.js
  server/src/schemas/index.js
  server/src/schemas/likes.js
  server/src/schemas/resetDatabase.js
  server/src/services/home.js
  server/src/services/likes.js
  server/src/services/property.js
  server/src/services/user.js
  server/src/utils/error.js
Labels: backend, API

#120 ISSUE-118 fix: fix url with search parameter
  client/src/components/Header/Menu.js
  client/src/components/SearchOption/SearchButtons/BedSelect.js
  client/src/components/SearchOption/SearchButtons/HomeType.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/components/SearchOption/SearchInput.js
  client/src/pages/Home/Home.js
Labels: bug, frontend

#137 ISSUE-128 fix: like List (Cover String -> Integer)
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyGrid.js
Labels: bug, frontend

#142 Home API: search by location title + beds
  server/src/models/home.js
  server/src/services/home.js
Labels: backend, API

#146 ISSUE-145 fix: like int -> string
  client/src/components/Property/PropertyCard.js
Labels: bug

#147 feat: Persistent user profile update (fetching + saving)
  client/src/components/User/UserProfileEdit.js
  client/src/redux/users/service.js
  server/src/controller/user.js
  server/src/models/user.js
  server/src/schemas/users.js
  server/src/services/user.js
Labels: frontend, backend

#149 fix : bug Save btn on detailed page
  client/src/components/Property/MenuItems.js
Labels: bug

#144 Issue 116: Pagination
  client/src/components/Property/PropertyGrid.js
  client/src/redux/home/reducer.js
  client/src/redux/home/service.js
  client/src/redux/property/service.js
  client/src/redux/search/reducer.js
  server/src/controller/home.js
  server/src/routes/home.js
Labels: frontend, backend

#151 User login & validation at API request
  .idea/workspace.xml
  client/package-lock.json
  client/package.json
  client/src/Router.js
  client/src/components/Header/Menu.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserInfo.js
  client/src/config.js
  client/src/index.js
  client/src/pages/Compare/Compare.js
  client/src/pages/Likes/Likes.js
  client/src/pages/Login/Login.js
  client/src/pages/Login/Logout.js
  client/src/pages/MyPage/MyPage.js
  client/src/redux/home/service.js
  client/src/redux/likes/service.js
  client/src/redux/property/service.js
  client/src/redux/users/actionTypes.js
  client/src/redux/users/reducer.js
  client/src/redux/users/service.js
  client/src/redux/users/thunks.js
  client/src/utils/storage.js
  server/.eslintrc
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/controller/auth.js
  server/src/controller/user.js
  server/src/data/data.js
  server/src/middleware/auth.js
  server/src/middleware/googleStrategy.js
  server/src/middleware/index.js
  server/src/routes/auth.js
  server/src/routes/home.js
  server/src/routes/index.js
  server/src/routes/property.js
  server/src/routes/user.js
  server/src/schemas/index.js
  server/src/schemas/likes.js
  server/src/server.js
  server/src/services/home.js
  server/src/services/user.js
Labels: enhancement, frontend, backend, API

#165 feat: feature flags for zillow api & auth
  server/.env-sample
  server/src/data/data.js
  server/src/middleware/auth.js
  server/src/models/home.js
  server/src/models/property.js
  server/src/schemas/propertyDetails.js
  server/src/server.js
  server/src/services/home.js
  server/src/services/property.js
Labels: enhancement, backend

#167 feat: handle property not found
  client/src/components/Property/ImageCarousel.js
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyNotFound.js
  client/src/pages/Compare/Compare.js
  client/src/pages/PropertyDetail/PropertyDetail.js
  client/src/utils/utils.js
  server/src/controller/property.js
  server/src/services/property.js
Labels: enhancement, frontend, backend

#169 fix: hometypes typo
  client/src/components/SearchOption/SearchButtons/HomeType.js
Labels: bug

#170 feat: Compare API
  server/src/controller/compare.js
  server/src/controller/index.js
  server/src/models/compare.js
  server/src/models/index.js
  server/src/routes/compare.js
  server/src/routes/index.js
  server/src/services/compare.js
  server/src/services/index.js
Labels: backend, API

#172 feat: add virtual tour on detailed page
  client/src/components/Property/VirtualTour.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: frontend

#182 ISSUE-180: Fix text-centering
  client/src/pages/Likes/Likes.js
Labels: frontend

#183 ISSUE-184: remove .css and replace to styled-component on Property Card/Grid
  client/public/index.html
  client/src/components/Footer/Footer.js
  client/src/components/Header/Header.js
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/DetailedInfo.js
  client/src/components/Property/PropertyCard.css
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyGrid.css
  client/src/components/Property/PropertyGrid.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserInfo.js
  client/src/global.js
  client/src/pages/Compare/Compare.js
  client/src/pages/Likes/Likes.js
  client/src/styles/theme.js
Labels: bug, frontend

#174 Issue 158
  client/src/assets/images/imgNotFound.png
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyImage.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/pages/Home/Home.js
Labels: bug, frontend

#175 ISSUE-150 fix : heart flickering bug (update redux seperately)
  client/src/redux/likes/reducer.js
  client/src/redux/likes/thunks.js
Labels: bug, frontend

#178 Issue 176 Nearby home Detailed page
  client/package-lock.json
  client/package.json
  client/src/components/Property/NearByHomes.js
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyGrid.js
  client/src/pages/Home/Home.js
  client/src/pages/Likes/Likes.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: frontend

#186 fix: Property img (merge resolved)
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyImage.js
  client/src/pages/Home/Home.js
Labels: bug, frontend

#193 ISSUE-192: handle nearbyhome empty state
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: bug, frontend

#195 Issue 161: chatbot - frontend
  client/package-lock.json
  client/src/components/Footer/Footer.js
Labels: frontend

#196 feat: place a button to navigate to prev page
  client/src/components/Property/PropertyTitle.js
  client/src/pages/Likes/Likes.js
Labels: frontend

#200 Issue 191 1) Add Reset BTN (change backend call logic) 2) URL modification
  client/src/components/SearchOption/SearchButtons/BedSelect.js
  client/src/components/SearchOption/SearchButtons/HomeType.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/pages/Home/Home.js
  client/src/redux/search/reducer.js
Labels: bug, enhancement, frontend

#207 fix: indentation fixed (ISSUE-161)
  client/src/components/Footer/Footer.js
Labels: bug

#202 ISSUE-199 feat: Footer Design
  client/src/components/Footer/Footer.js
  client/src/components/Footer/FooterSocial.js
Labels: frontend

#210 fix: import order fixed
  client/src/components/Footer/Footer.js
Labels: bug, frontend

#211 ISSUE-100-Merge feat: Mapbox
  client/src/components/Property/MapBox.js
  client/src/config.js
Labels: frontend

#212 ISSUE- 201 fix: change the min/max logic so that can delete when num < 10
  client/src/components/SearchOption/SearchButtons/PriceRange.js
Labels: bug, frontend

#213 Issue 203 SNS share
  client/src/components/Property/MenuItems.js
  client/src/components/Property/ShareMenu.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: enhancement, frontend

#218 use token for auth verification
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/components/Footer/Footer.js
  client/src/components/Footer/FooterSocial.js
  client/src/components/Header/Header.js
  client/src/components/Property/MapBox.js
  client/src/components/Property/MenuItems.js
  client/src/components/Property/PropertyCard.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserProfileEdit.js
  client/src/config.js
  client/src/pages/Compare/Compare.js
  client/src/pages/Home/Home.js
  client/src/pages/Likes/Likes.js
  client/src/pages/Login/Login.js
  client/src/pages/Login/Logout.js
  client/src/pages/MyPage/MyPage.js
  client/src/pages/PropertyDetail/PropertyDetail.js
  client/src/redux/home/service.js
  client/src/redux/home/thunks.js
  client/src/redux/likes/service.js
  client/src/redux/likes/thunks.js
  client/src/redux/property/service.js
  client/src/redux/property/thunks.js
  client/src/redux/users/service.js
  client/src/redux/users/thunks.js
  server/.eslintrc
  server/package-lock.json
  server/package.json
  server/src/controller/user.js
  server/src/middleware/auth.js
  server/src/middleware/googleStrategy.js
  server/src/routes/auth.js
  server/src/server.js
  server/src/utils/featureFlags.js
Labels: frontend, backend, infra
