Repository thekimsplustwo/VanCityPropertyPulse, pull requests merged in 2023-06, with the labels that each got.

#14 feat: implement user component
  client/package-lock.json
  client/package.json
  client/src/components/User/DummyUser.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserFavourites.js
  client/src/components/User/UserInfo.js
  client/src/pages/MyPage/MyPage.js
  client/src/styles/UserProfile.js
Labels: frontend

#15 ISSUE-11: create NavBar, Search Input with Menu
  client/src/components/Header/Header.js
  client/src/components/Header/Input.js
  client/src/components/Header/Menu.js
  client/src/components/Header/Nav.js
Labels: frontend

#23 Issue 22
  .vscode/settings.json
  client/src/assets/images/demoHouse.jpg
  client/src/assets/images/src.md
  client/src/components/Property/PropertyCard.css
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyGrid.css
  client/src/components/Property/PropertyGrid.js
  client/src/pages/Home/Home.js
Labels: frontend

#25 ISSUE19 - 1) Input search disappears 2) Links 3) Fontcolor
  client/src/components/Header/Menu.js
  client/src/components/Header/Nav.js
  client/src/components/SearchOption/Input.js
Labels: bug, frontend

#38 Issue 30
  client/package-lock.json
  client/src/components/Header/Menu.js
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/DetailedInfo.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserPageLeft.js
  client/src/pages/MyPage/MyPage.js
  client/src/pages/PropertyDetail/PropertyDetail.js
  client/src/styles/theme.js
Labels: frontend

#45 ISSUE- 44 Search Component
  client/src/assets/images/searchComponent.jpg
  client/src/components/SearchOption/Input.js
  client/src/components/SearchOption/SearchComponent.js
  client/src/components/SearchOption/SearchInput.js
  client/src/components/SearchOption/neighborhoods.js
  client/src/pages/Home/Home.js
Labels: frontend

#55 Likes backend api for mock data + Middleware auth
  server/.eslintrc
  server/src/controller/home.js
  server/src/controller/index.js
  server/src/controller/likes.js
  server/src/controller/property.js
  server/src/controller/user.js
  server/src/data/data.js
  server/src/middleware/auth.js
  server/src/models/home.js
  server/src/models/index.js
  server/src/models/likes.js
  server/src/models/mockHome.js
  server/src/models/mockLikes.js
  server/src/models/mockProperty.js
  server/src/models/property.js
  server/src/models/user.js
  server/src/routes/home.js
  server/src/routes/index.js
  server/src/routes/likes.js
  server/src/routes/user.js
  server/src/services/index.js
  server/src/services/likes.js
  server/src/services/user.js
  server/src/utils/error.js
Labels: backend, API

#51 ISSUE 44 (continue) - Search Options Button
  client/src/components/Header/Menu.js
  client/src/components/SearchOption/SearchButtons/BedSelect.js
  client/src/components/SearchOption/SearchButtons/HomeType.js
  client/src/components/SearchOption/SearchButtons/HomeTypeMenuItem.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/components/SearchOption/SearchComponent.js
  client/src/components/SearchOption/SearchOptions.js
Labels: frontend

#62 fix: Bug- components are rendered over nav bar
  client/src/components/Header/Header.js
Labels: bug, frontend

#61 My page: send email in header as a token for auth to backend
  client/src/redux/users/service.js
Labels: frontend

#60 Add Likes Pages with GET added, mapping Detailed Pages data
  client/src/components/Likes/LikesDetails.js
  client/src/components/Property/DetailedInfo.js
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyGrid.js
  client/src/pages/Home/Home.js
  client/src/pages/Likes/Likes.js
  client/src/redux/likes/actionTypes.js
  client/src/redux/likes/reducer.js
  client/src/redux/likes/service.js
  client/src/redux/likes/thunks.js
  client/src/redux/store.js
  server/src/controller/likes.js
  server/src/services/property.js
Labels: frontend, backend

#64 Issue 30: Put 3 Boxes in User Profile Page
  client/src/pages/MyPage/MyPage.js
  client/src/styles/theme.js
Labels: frontend

#69 ISSUE- 56 fix: Bug- components are rendered over nav bar
  client/src/components/Header/Header.js
  client/src/components/Header/Menu.js
Labels: bug, frontend

#70 ISSUE-68: fix: Like and Unlike Button in PropertyCard
  client/src/components/Property/PropertyCard.js
  client/src/pages/Home/Home.js
  client/src/redux/likes/thunks.js
Labels: bug, frontend

#71 Add Clear All button
  client/src/components/Property/DetailedInfo.js
  client/src/pages/Likes/Likes.js
  client/src/pages/PropertyDetail/PropertyDetail.js
  client/src/redux/likes/actionTypes.js
  client/src/redux/likes/reducer.js
  client/src/redux/likes/service.js
  client/src/redux/likes/thunks.js
  server/package-lock.json
  server/src/controller/likes.js
  server/src/models/mockLikes.js
  server/src/routes/likes.js
  server/src/services/likes.js
Labels: frontend, backend, API

#72 style: increase the space between description lines
  client/src/components/Property/DetailedInfo.js
Labels: frontend

#73 Issue 57
  client/.eslintrc
  client/src/Router.js
  client/src/components/Header/Menu.js
  client/src/components/User/MoreOptions.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserFavourites.js
  client/src/components/User/UserInfo.js
  client/src/components/User/UserPageLeft.js
  client/src/components/User/UserProfileEdit.js
  client/src/pages/MyPage/MyPage.js
  client/src/redux/users/actionTypes.js
  client/src/redux/users/reducer.js
  client/src/redux/users/service.js
  client/src/redux/users/thunks.js
  server/src/controller/user.js
  server/src/models/mockUser.js
  server/src/models/user.js
  server/src/routes/user.js
  server/src/services/user.js
Labels: bug, frontend, backend

#76 fix: likes page footer position
  client/src/pages/Likes/Likes.js
Labels: frontend

#78 feat: open linked page in new tab
  client/src/components/Footer/Footer.js
Labels: frontend

#79 refactor: redux init state mapped to its property
  client/src/components/Header/Menu.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserInfo.js
  client/src/components/User/UserProfileEdit.js
  client/src/pages/MyPage/MyPage.js
  client/src/pages/PropertyDetail/PropertyDetail.js
  client/src/redux/property/reducer.js
  client/src/redux/users/reducer.js
Labels: frontend

#81 style: Adjust height
  client/src/components/User/MoreOptions.js
  client/src/components/User/UserInfo.js
Labels: frontend

#82 Issue 57: Buttons in the User Edit Form
  client/src/components/User/UserProfileEdit.js
  package-lock.json
Labels: frontend

#104 style: Changed the width of the Box component in MyPage to 100%
  client/src/pages/MyPage/MyPage.js
Labels: frontend

#106 ISSUE-91 style: remove unnecessary components and button
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/DetailedInfo.js
  client/src/components/Property/MenuItems.js
Labels: frontend

#105 style: adjust min-width and add scroll bar for description
  client/src/components/Property/DetailedInfo.js
Labels: frontend
