Repository thekimsplustwo/VanCityPropertyPulse, pull requests merged in 2023-08, with the labels that each got.

#239 ISSUE-238: hide whitelist to .env
  server/src/server.js
Labels: backend

#240 ISSUE-215: compare redux
  client/src/pages/Compare/Compare.js
  client/src/redux/property/actionTypes.js
  client/src/redux/property/reducer.js
  client/src/redux/property/service.js
  client/src/redux/property/thunks.js
Labels: frontend

#247 ISSUE-246: add endpoint prefix 'api'
  server/package-lock.json
  server/package.json
  server/src/controller/auth.js
  server/src/middleware/auth.js
  server/src/middleware/googleStrategy.js
  server/src/server.js
Labels: backend

#249 ISSUE-234: mapbox rendering on combined server
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/components/Property/MapBox.js
Labels: bug, frontend

#251 ISSUE-250 add GENERATE_SOURCEMAP=false option on client build script
  client/package.json
Labels: frontend

#252 refactor: remove SERVER_URL env
  server/src/controller/auth.js
  server/src/middleware/auth.js
  server/src/middleware/googleStrategy.js
Labels: backend

#243 ISSUE-236: adjust heights of the components in MyPage
  client/package-lock.json
  client/src/components/User/UserCard.js
  client/src/components/User/UserPageLeft.js
Labels: frontend

#244 ISSUE-242: align the "delete" button with the other components
  client/src/components/Compare/CompareDeleteButton.js
Labels: bug, frontend

#245 ISSUE-237: Align top + texts to stay in the grid
  client/src/components/Property/DetailedInfo.js
  client/src/components/Property/MapBox.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: bug, frontend

#263 ISSUE- 254 fix: minor improvement
  client/src/components/Footer/Footer.js
  client/src/components/Footer/FooterSocial.js
  client/src/components/Header/Menu.js
  client/src/components/SearchOption/SearchInput.js
  client/src/pages/Home/Home.js
Labels: enhancement, frontend

#258 ISSUE-257: return only property information in array
  client/playwright-report/index.html
  server/src/models/compare.js
Labels: backend

#262 Issue-241: add playwright - init test
  .github/workflow/playwright.yml
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/playwright.config.js
  client/src/components/Property/ShareMenu.js
  client/src/config.js
  client/tests/config.js
  client/tests/test.spec.js
  server/package-lock.json
Labels: test

#267 ISSUE-265- Hompage feat: Homepage Mobile friendly
  client/src/components/SearchOption/SearchButtons/BedSelect.js
  client/src/components/SearchOption/SearchButtons/HomeType.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/components/SearchOption/SearchInput.js
  client/src/components/SearchOption/SearchOptions.js
  client/src/pages/Home/Home.js
Labels: enhancement, frontend

#268 ISSUE-265-Like page feat: Like page Mobile friendly
  client/src/pages/Likes/Likes.js
Labels: enhancement, frontend

#273 ISSUE-265 Mypage feat: MyPage Mobile friendly
  client/src/components/User/MoreOptions.js
  client/src/components/User/UserProfileEdit.js
  client/src/pages/MyPage/MyPage.js
Labels: enhancement, frontend

#274 ISSUE-265-Detail feat: Detail Page (Mobile)
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/DetailedInfo.js
  client/src/components/Property/Image.js
  client/src/components/Property/ImageCarousel.js
  client/src/components/Property/MapBox.js
  client/src/components/Property/NearByHomes.js
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyTitle.js
  client/src/components/Property/WalkScore.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: enhancement, frontend

#277 ISSUE276 , feat: Neighbourhood details
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/FeaturesSection.js
  client/src/components/Property/SchoolCard.js
  client/src/components/Property/TransitScore.js
  client/src/components/Property/WalkScore.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: enhancement, frontend

#272 ISSUE-209: refactor: refactored DetailedInfo
  client/src/components/Property/DetailedInfo.js
Labels: enhancement

#269 ISSUE-260: Edit User Profile (front-end)
  client/src/components/User/UserCard.js
  client/src/components/User/UserProfileEdit.js
Labels: enhancement, frontend

#275 ISSUE-261: 'Nearby Me' in MyPage
  client/src/components/Property/NearByHomes.js
  client/src/components/Property/NearbyProperties.js
  client/src/components/User/NearbyMe.js
  client/src/pages/MyPage/MyPage.js
Labels: frontend

#285 Detail feat: 1) install x-chart 2) price ComparisonBar
  client/package-lock.json
  client/package.json
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/PriceComparisonBar.js
Labels: enhancement, frontend

#278 ISSUE 264 / feat: 1) like/compare fix height 2) compare Mobile friendly
  client/src/pages/Compare/Compare.js
  client/src/pages/Compare/Modal.js
  client/src/pages/Likes/Likes.js
Labels: enhancement, frontend

#282 ISSUE-266 fix: mapbox not update fix
  client/src/components/Property/MapBox.js
Labels: bug, frontend

#292 ISSUE-281: compare page calling compare api + playwright setup on github
  .github/workflows/playwright.yml
  client/.gitignore
  client/playwright-report/index.html
  client/src/components/Compare/CompareDeleteButton.js
  client/src/components/Compare/CompareProps.js
  client/src/components/Property/ImageCarousel.js
  client/src/pages/Compare/Compare.js
  client/src/pages/Home/Home.js
  client/src/pages/PropertyDetail/PropertyDetail.js
  client/src/redux/property/service.js
  client/tests/config.js
  client/tests/test.spec.js
  server/src/controller/property.js
  server/src/data/data.js
  server/src/schemas/likes.js
  server/src/server.js
Labels: frontend, backend, database

#299 ISSUE-295: Data scrapping
  client/src/components/Footer/Footer.js
  server/src/models/home.js
  server/src/models/property.js
  server/src/schemas/rawProperties.js
  server/src/schemas/rawPropertyDetail.js
  server/src/schemas/resetDatabase.js
  server/src/services/home.js
  server/src/services/property.js
  server/src/utils/error.js
Labels: backend, database

#297 ISSUE-296 feat: 1) median 2) more feature
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/PriceComparisonBar.js
Labels: enhancement, frontend

#288 ISSUE-286: Fix the size of min/max input boxes
  client/src/components/SearchOption/SearchButtons/PriceRange.js
Labels: bug, frontend

#300 ISSUE-294: Only list properties whose listingStatus is "FOR_SALE"
  client/src/components/User/NearbyMe.js
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: frontend

#289 Refactor: MyPage (Right Panel)
  client/src/components/User/CenteredGrid.js
  client/src/components/User/MoreOptions.js
Labels: enhancement

#303 ISSUE-302: likes schema & likes button rendering
  client/src/components/Compare/CompareDeleteButton.js
  client/src/components/Property/MenuItems.js
  client/src/components/Property/PropertyCard.js
  client/src/pages/Compare/Modal.js
  client/src/redux/likes/reducer.js
  client/src/redux/likes/thunks.js
  client/src/styles/theme.js
  server/src/models/compare.js
  server/src/schemas/likes.js
Labels: bug, frontend, database

#308 ISSUE-307: likes button onclick target
  client/src/components/Property/MenuItems.js
Labels: frontend

#306 ISSUE-305: navigate to property detail page at click the property image on…
  client/src/components/Property/ImageCarousel.js
  client/src/components/User/MoreOptions.js
  client/src/pages/Compare/Compare.js
Labels: frontend

#311 feat: remove average
  client/src/components/Property/PriceComparisonBar.js
Labels: enhancement, frontend

#315 ISSUE-314 feat: remove useless locations
  client/src/components/SearchOption/neighborhoods.js
Labels: bug, frontend

#309 ISSUE-283: detailed page data displaying
  client/src/components/Property/DetailedInfo.js
Labels: frontend

#316 feat: don't show price per sqft and strata fee if they are undefined/…
  client/src/components/Property/DetailedInfo.js
  server/package-lock.json
Labels: bug

#313 ISSUE-312: Fix the Issues for Nearby Me + Nearby Homes
  client/src/components/User/NearbyMe.js
  client/src/pages/PropertyDetail/PropertyDetail.js
  client/src/redux/home/reducer.js
Labels: bug, frontend

#319 ISSUE-270: return [] if currentpage > totalpage
  client/src/components/Property/PropertyGrid.js
  client/src/components/Property/PropertyNotFound.js
  server/src/services/home.js
Labels: frontend, backend

#327 ISSUE-325 fix: when no region data footer comes up
  client/src/pages/MyPage/MyPage.js
Labels: bug, frontend

#332 ISSUE-331: Refresh the page after user updates their profile info
  client/src/components/User/UserProfileEdit.js
  client/src/pages/MyPage/MyPage.js
Labels: bug

#338 Issue 337: fix the alignment on detailed page
  client/src/pages/PropertyDetail/PropertyDetail.js
Labels: enhancement

#335 ISSUE-334: null check to prevent errors on Compare page
  client/src/pages/Compare/Modal.js
Labels: bug

#339 ISSUE-336: chatbot opens in the current window
  client/src/components/Footer/Footer.js
Labels: frontend

#333 ISSUE-330: Pagination only shows in '/home'
  client/src/components/Property/PropertyGrid.js
  client/src/pages/Compare/Modal.js
  client/src/pages/Home/Home.js
Labels: frontend

#344 Style: Cleaned the codes (front-end)
  client/src/Router.js
  client/src/components/Compare/CompareProps.js
  client/src/components/Footer/Footer.js
  client/src/components/Footer/FooterSocial.js
  client/src/components/Header/Header.js
  client/src/components/Header/Menu.js
  client/src/components/Header/Nav.js
  client/src/components/Likes/LikesDetails.js
  client/src/components/Property/AdditonalInfo.js
  client/src/components/Property/DetailedInfo.js
  client/src/components/Property/FeaturesSection.js
  client/src/components/Property/ImageCarousel.js
  client/src/components/Property/MapBox.js
  client/src/components/Property/MenuItems.js
  client/src/components/Property/NearByHomes.js
  client/src/components/Property/NearbyProperties.js
  client/src/components/Property/PropertyCard.js
  client/src/components/Property/PropertyImage.js
  client/src/components/Property/PropertyTitle.js
  client/src/components/Property/ShareMenu.js
  client/src/components/Property/TransitScore.js
  client/src/components/Property/VirtualTour.js
  client/src/components/Property/WalkScore.js
  client/src/components/SearchOption/SearchButtons/HomeType.js
  client/src/components/SearchOption/SearchButtons/HomeTypeMenuItem.js
  client/src/components/SearchOption/SearchButtons/PriceRange.js
  client/src/components/SearchOption/SearchComponent.js
  client/src/components/SearchOption/SearchInput.js
  client/src/components/SearchOption/SearchOptions.js
  client/src/components/User/NearbyMe.js
  client/src/components/User/UserCard.js
  client/src/components/User/UserProfileEdit.js
  client/src/index.css
  client/src/index.js
  client/src/pages/Compare/Compare.js
  client/src/pages/Compare/Modal.js
  client/src/pages/Home/DummyHome.js
  client/src/pages/Home/Home.js
  client/src/pages/Likes/Likes.js
  client/src/pages/Login/Login.js
  client/src/redux/home/reducer.js
  client/src/redux/search/reducer.js
  client/src/redux/store.js
  client/src/styles/theme.js
  client/src/utils/utils.js
  client/tests/test.spec.js
Labels: frontend
